[package]
name = "linera_prometheus_parsing"
version = "0.1.0"
license = "MIT"
authors = ["Mathieu Dutour Sikiric <Mathieu.Dutour@gmail.com>"]

[[bin]]
name = "parsing_prometheus_run"
path = "src/main_extract_metrics.rs"

[dependencies]
html_parser = "0.6.3"
chrono = "0.4.38"
thiserror = "1.0.38"
yaml-rust = "0.4"
serde = "1.0"
serde_yaml = "0.9"
serde_json = "1.0.111"